# Generated by Django 3.2 on 2022-05-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_newsletterform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetterForm',
            new_name='NewsLetterRecepients',
        ),
    ]
